---
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
- name: Add the user 'dotsenkois', appending the group 'docker' the user's groups
  ansible.builtin.user:
    name: dotsenkois
    groups: docker
    append: yes