---
- name: Update all packages to their latest version
  become: true
  apt: 
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600 

- name: "Install conntrack, iptables"
  become: true
  apt:
    pkg:
    - conntrack
    - iptables
  
- name: "Install docker"
  pip:
    pkg:
    - docker
