---
- name: Update all packages to their latest version
  become: true
  apt: 
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600 

- name: "Install docker.io, conntrack, iptables"
  become: true
  apt:
    pkg:
    - docker.io
    - conntrack
    - iptables