---
- name: Update all packages to their latest version
  become: true
  apt: 
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600 

- name: "Install conntrack, iptables, docker"
  become: true
  apt:
    pkg:
    - conntrack
    - iptables
    - docker.io
- name: Change owner of docker
  become: true
  ansible.builtin.file:
    path: /usr/bin/dockerd
    owner: dotsenkois
    group: dotsenkois
- name: Restart service docker, in all cases
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted  

